//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAW.ExamenFinal.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CopiaPelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CopiaPelicula()
        {
            this.Renta = new HashSet<Renta>();
        }
    
        public int IdCopiaPelicula { get; set; }
        public Nullable<int> Medio { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string NombreOriginal { get; set; }
        public int PublicadaEn { get; set; }
        public string Genero { get; set; }
        public Nullable<bool> PerdidaDanada { get; set; }
        public Nullable<System.DateTime> FechaPerdidaDanada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renta> Renta { get; set; }
    }
}
